//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Mvp.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Mvp.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the official Microsoft Most Valuable Professional (MVP) Award program app.
        ///Microsoft MVP award is given to exceptional, independent community leaders who share their passion, technical expertise, and real-world knowledge of Microsoft products with others.Microsoft MVPs can use this app to access their profile,  contribution data, as well as automating several different tasks creating efficiency in daily tasks..
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Articles.
        /// </summary>
        public static string AnnualQuantityTipTextDefault {
            get {
                return ResourceManager.GetString("AnnualQuantityTipTextDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Articles.
        /// </summary>
        public static string AnnualQuantityTipTextForArticle {
            get {
                return ResourceManager.GetString("AnnualQuantityTipTextForArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Books.
        /// </summary>
        public static string AnnualQuantityTipTextForBook {
            get {
                return ResourceManager.GetString("AnnualQuantityTipTextForBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Conferences.
        /// </summary>
        public static string AnnualQuantityTipTextForConference {
            get {
                return ResourceManager.GetString("AnnualQuantityTipTextForConference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Events provided.
        /// </summary>
        public static string AnnualQuantityTipTextForFeedback {
            get {
                return ResourceManager.GetString("AnnualQuantityTipTextForFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Threads moderated.
        /// </summary>
        public static string AnnualQuantityTipTextForForumModerator {
            get {
                return ResourceManager.GetString("AnnualQuantityTipTextForForumModerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Answers.
        /// </summary>
        public static string AnnualQuantityTipTextForForumParticipation {
            get {
                return ResourceManager.GetString("AnnualQuantityTipTextForForumParticipation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Mentees.
        /// </summary>
        public static string AnnualQuantityTipTextForMentorship {
            get {
                return ResourceManager.GetString("AnnualQuantityTipTextForMentorship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string AnnualQuantityTipTextForOpenSource {
            get {
                return ResourceManager.GetString("AnnualQuantityTipTextForOpenSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual quantity.
        /// </summary>
        public static string AnnualQuantityTipTextForOther {
            get {
                return ResourceManager.GetString("AnnualQuantityTipTextForOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Posts.
        /// </summary>
        public static string AnnualQuantityTipTextForPosts {
            get {
                return ResourceManager.GetString("AnnualQuantityTipTextForPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Projects.
        /// </summary>
        public static string AnnualQuantityTipTextForProject {
            get {
                return ResourceManager.GetString("AnnualQuantityTipTextForProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Samples.
        /// </summary>
        public static string AnnualQuantityTipTextForSamples {
            get {
                return ResourceManager.GetString("AnnualQuantityTipTextForSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts.
        /// </summary>
        public static string AnnualQuantityTipTextForSiteOwner {
            get {
                return ResourceManager.GetString("AnnualQuantityTipTextForSiteOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Posts.
        /// </summary>
        public static string AnnualQuantityTipTextForSocialMedia {
            get {
                return ResourceManager.GetString("AnnualQuantityTipTextForSocialMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talks.
        /// </summary>
        public static string AnnualQuantityTipTextForSpeaking {
            get {
                return ResourceManager.GetString("AnnualQuantityTipTextForSpeaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual quantity.
        /// </summary>
        public static string AnnualQuantityTipTextForTranslationReviewFeedbackEditing {
            get {
                return ResourceManager.GetString("AnnualQuantityTipTextForTranslationReviewFeedbackEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meetings.
        /// </summary>
        public static string AnnualQuantityTipTextForUserGroupOwner {
            get {
                return ResourceManager.GetString("AnnualQuantityTipTextForUserGroupOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Videos.
        /// </summary>
        public static string AnnualQuantityTipTextForVideo {
            get {
                return ResourceManager.GetString("AnnualQuantityTipTextForVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Videos.
        /// </summary>
        public static string AnnualQuantityTipTextForWebcast {
            get {
                return ResourceManager.GetString("AnnualQuantityTipTextForWebcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Posts.
        /// </summary>
        public static string AnnualQuantityTipTextForWebsitePosts {
            get {
                return ResourceManager.GetString("AnnualQuantityTipTextForWebsitePosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Views.
        /// </summary>
        public static string AnnualReachTipTextDefault {
            get {
                return ResourceManager.GetString("AnnualReachTipTextDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Views.
        /// </summary>
        public static string AnnualReachTipTextForArticle {
            get {
                return ResourceManager.GetString("AnnualReachTipTextForArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copies sold.
        /// </summary>
        public static string AnnualReachTipTextForBook {
            get {
                return ResourceManager.GetString("AnnualReachTipTextForBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Visitors.
        /// </summary>
        public static string AnnualReachTipTextForConference {
            get {
                return ResourceManager.GetString("AnnualReachTipTextForConference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Feedbacks provided.
        /// </summary>
        public static string AnnualReachTipTextForFeedback {
            get {
                return ResourceManager.GetString("AnnualReachTipTextForFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual reach.
        /// </summary>
        public static string AnnualReachTipTextForForumModerator {
            get {
                return ResourceManager.GetString("AnnualReachTipTextForForumModerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View of answers.
        /// </summary>
        public static string AnnualReachTipTextForForumParticipation {
            get {
                return ResourceManager.GetString("AnnualReachTipTextForForumParticipation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual reach.
        /// </summary>
        public static string AnnualReachTipTextForMentorship {
            get {
                return ResourceManager.GetString("AnnualReachTipTextForMentorship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commits.
        /// </summary>
        public static string AnnualReachTipTextForOpenSource {
            get {
                return ResourceManager.GetString("AnnualReachTipTextForOpenSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual reach.
        /// </summary>
        public static string AnnualReachTipTextForOther {
            get {
                return ResourceManager.GetString("AnnualReachTipTextForOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Unique Visitors.
        /// </summary>
        public static string AnnualReachTipTextForPosts {
            get {
                return ResourceManager.GetString("AnnualReachTipTextForPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Downloads.
        /// </summary>
        public static string AnnualReachTipTextForProject {
            get {
                return ResourceManager.GetString("AnnualReachTipTextForProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Downloads.
        /// </summary>
        public static string AnnualReachTipTextForSamples {
            get {
                return ResourceManager.GetString("AnnualReachTipTextForSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitors.
        /// </summary>
        public static string AnnualReachTipTextForSiteOwner {
            get {
                return ResourceManager.GetString("AnnualReachTipTextForSiteOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Followers.
        /// </summary>
        public static string AnnualReachTipTextForSocialMedia {
            get {
                return ResourceManager.GetString("AnnualReachTipTextForSocialMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendees of talks.
        /// </summary>
        public static string AnnualReachTipTextForSpeaking {
            get {
                return ResourceManager.GetString("AnnualReachTipTextForSpeaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual reach.
        /// </summary>
        public static string AnnualReachTipTextForTranslationReviewFeedbackEditing {
            get {
                return ResourceManager.GetString("AnnualReachTipTextForTranslationReviewFeedbackEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string AnnualReachTipTextForUserGroupOwner {
            get {
                return ResourceManager.GetString("AnnualReachTipTextForUserGroupOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Views.
        /// </summary>
        public static string AnnualReachTipTextForVideo {
            get {
                return ResourceManager.GetString("AnnualReachTipTextForVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Views.
        /// </summary>
        public static string AnnualReachTipTextForWebcast {
            get {
                return ResourceManager.GetString("AnnualReachTipTextForWebcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Unique Visitors.
        /// </summary>
        public static string AnnualReachTipTextForWebsitePosts {
            get {
                return ResourceManager.GetString("AnnualReachTipTextForWebsitePosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit a contribution.
        /// </summary>
        public static string ContributionDetailTitleForEditing {
            get {
                return ResourceManager.GetString("ContributionDetailTitleForEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new contribution.
        /// </summary>
        public static string ContributionDetailTitleForNew {
            get {
                return ResourceManager.GetString("ContributionDetailTitleForNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright {0} Microsoft.
        /// </summary>
        public static string CopyrightFormat {
            get {
                return ResourceManager.GetString("CopyrightFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NetworkError:Please check your network and try again.
        /// </summary>
        public static string DefaultNetworkErrorString {
            get {
                return ResourceManager.GetString("DefaultNetworkErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built in C# with Xamarin.
        /// </summary>
        public static string DevToolsInfo {
            get {
                return ResourceManager.GetString("DevToolsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DialogCancel {
            get {
                return ResourceManager.GetString("DialogCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, Delete.
        /// </summary>
        public static string DialogConfirmTextForDelete {
            get {
                return ResourceManager.GetString("DialogConfirmTextForDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check connectivity to proceed to MVP account sign in..
        /// </summary>
        public static string DialogDescriptionForCheckNetwork {
            get {
                return ResourceManager.GetString("DialogDescriptionForCheckNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like something went wrong. Please check your connection.. Error: {0} unable to load.
        /// </summary>
        public static string DialogDescriptionForCheckNetworkFormat {
            get {
                return ResourceManager.GetString("DialogDescriptionForCheckNetworkFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check connectivity to submit contribution..
        /// </summary>
        public static string DialogDescriptionForCheckNetworkFormat1 {
            get {
                return ResourceManager.GetString("DialogDescriptionForCheckNetworkFormat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this contribution?.
        /// </summary>
        public static string DialogDescriptionForDelete {
            get {
                return ResourceManager.GetString("DialogDescriptionForDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open your browser..
        /// </summary>
        public static string DialogDescriptionForError {
            get {
                return ResourceManager.GetString("DialogDescriptionForError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to validate MVP status, please login again with your MVP credentials..
        /// </summary>
        public static string DialogDescriptionForInvalidCredentials {
            get {
                return ResourceManager.GetString("DialogDescriptionForInvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MVP contribution has been saved successfully. Thank you for your contribution..
        /// </summary>
        public static string DialogDescriptionForSaved {
            get {
                return ResourceManager.GetString("DialogDescriptionForSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like something went wrong. Please check your connection and submit again. Error: {0} unable to save&quot;.
        /// </summary>
        public static string DialogDescriptionForUnableSave {
            get {
                return ResourceManager.GetString("DialogDescriptionForUnableSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to sign out?.
        /// </summary>
        public static string DialogForSignoutConfirmTipText {
            get {
                return ResourceManager.GetString("DialogForSignoutConfirmTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, sign out.
        /// </summary>
        public static string DialogForSignoutOKText {
            get {
                return ResourceManager.GetString("DialogForSignoutOKText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string DialogLoading {
            get {
                return ResourceManager.GetString("DialogLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string DialogOK {
            get {
                return ResourceManager.GetString("DialogOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        public static string DialogSaving {
            get {
                return ResourceManager.GetString("DialogSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Connectivity.
        /// </summary>
        public static string DialogTitleForCheckNetwork {
            get {
                return ResourceManager.GetString("DialogTitleForCheckNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Contribution?.
        /// </summary>
        public static string DialogTitleForDelete {
            get {
                return ResourceManager.GetString("DialogTitleForDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string DialogTitleForError {
            get {
                return ResourceManager.GetString("DialogTitleForError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Contributions....
        /// </summary>
        public static string DialogTitleForLoadingContribution {
            get {
                return ResourceManager.GetString("DialogTitleForLoadingContribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading profile....
        /// </summary>
        public static string DialogTitleForLoadingProfile {
            get {
                return ResourceManager.GetString("DialogTitleForLoadingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved!.
        /// </summary>
        public static string DialogTitleForSaved {
            get {
                return ResourceManager.GetString("DialogTitleForSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out?.
        /// </summary>
        public static string DialogTitleForSignout {
            get {
                return ResourceManager.GetString("DialogTitleForSignout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected culture identifier.
        /// </summary>
        public static string ExpectedCultureIdentifier {
            get {
                return ResourceManager.GetString("ExpectedCultureIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a numerical field..
        /// </summary>
        public static string FieldMustbeNumberMessageText {
            get {
                return ResourceManager.GetString("FieldMustbeNumberMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid url.
        /// </summary>
        public static string InvalidUrlMessageText {
            get {
                return ResourceManager.GetString("InvalidUrlMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AWARD CATEGORIES.
        /// </summary>
        public static string LabelForAwardCategories {
            get {
                return ResourceManager.GetString("LabelForAwardCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contribution Area.
        /// </summary>
        public static string LabelForContributionArea {
            get {
                return ResourceManager.GetString("LabelForContributionArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of contribution.
        /// </summary>
        public static string LabelForContributionDate {
            get {
                return ResourceManager.GetString("LabelForContributionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title of contribution.
        /// </summary>
        public static string LabelForContributionTitle {
            get {
                return ResourceManager.GetString("LabelForContributionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contribution type.
        /// </summary>
        public static string LabelForContributionType {
            get {
                return ResourceManager.GetString("LabelForContributionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string LabelForDescription {
            get {
                return ResourceManager.GetString("LabelForDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIRST AWARDED.
        /// </summary>
        public static string LabelForFirstAward {
            get {
                return ResourceManager.GetString("LabelForFirstAward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # OF AWARDS.
        /// </summary>
        public static string LabelForNumberOfAward {
            get {
                return ResourceManager.GetString("LabelForNumberOfAward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string LabelForURL {
            get {
                return ResourceManager.GetString("LabelForURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility.
        /// </summary>
        public static string LabelForVisibility {
            get {
                return ResourceManager.GetString("LabelForVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn about MVP program.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field exceeded the maximum length.
        /// </summary>
        public static string MaxLengthMessageText {
            get {
                return ResourceManager.GetString("MaxLengthMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NetworkError:{0}.
        /// </summary>
        public static string NetworkErrorFormatString {
            get {
                return ResourceManager.GetString("NetworkErrorFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string PageTitleForLogOn {
            get {
                return ResourceManager.GetString("PageTitleForLogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About MVP.
        /// </summary>
        public static string PageTitleForSetting {
            get {
                return ResourceManager.GetString("PageTitleForSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $&quot;Unable to refresh token: {0}&quot;.
        /// </summary>
        public static string RefreshTokenExceptionTip {
            get {
                return ResourceManager.GetString("RefreshTokenExceptionTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing tokens....
        /// </summary>
        public static string RefreshTokenTip {
            get {
                return ResourceManager.GetString("RefreshTokenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        public static string RequiredFieldMessageText {
            get {
                return ResourceManager.GetString("RequiredFieldMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Subscribers.
        /// </summary>
        public static string SecondAnnualQuantityTipTextForPosts {
            get {
                return ResourceManager.GetString("SecondAnnualQuantityTipTextForPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Posts.
        /// </summary>
        public static string SecondAnnualQuantityTipTextForumParticipation {
            get {
                return ResourceManager.GetString("SecondAnnualQuantityTipTextForumParticipation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Subscribers.
        /// </summary>
        public static string SecondAnnualQuantityTipTextForWebsitePosts {
            get {
                return ResourceManager.GetString("SecondAnnualQuantityTipTextForWebsitePosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsButton {
            get {
                return ResourceManager.GetString("SettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to MVP account.
        /// </summary>
        public static string SigninTo {
            get {
                return ResourceManager.GetString("SigninTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string SignoutButton {
            get {
                return ResourceManager.GetString("SignoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributions.
        /// </summary>
        public static string TabTitleForContributions {
            get {
                return ResourceManager.GetString("TabTitleForContributions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        public static string TabTitleForProfile {
            get {
                return ResourceManager.GetString("TabTitleForProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        public static string VersionFormat {
            get {
                return ResourceManager.GetString("VersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
