//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVP.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MVP.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AnnualQuantityTipTextDefault {
            get {
                return ResourceManager.GetString("AnnualQuantityTipTextDefault", resourceCulture);
            }
        }
        
        public static string AnnualQuantityTipTextForArticle {
            get {
                return ResourceManager.GetString("AnnualQuantityTipTextForArticle", resourceCulture);
            }
        }
        
        public static string AnnualQuantityTipTextForBook {
            get {
                return ResourceManager.GetString("AnnualQuantityTipTextForBook", resourceCulture);
            }
        }
        
        public static string AnnualQuantityTipTextForConference {
            get {
                return ResourceManager.GetString("AnnualQuantityTipTextForConference", resourceCulture);
            }
        }
        
        public static string AnnualQuantityTipTextForFeedback {
            get {
                return ResourceManager.GetString("AnnualQuantityTipTextForFeedback", resourceCulture);
            }
        }
        
        public static string AnnualQuantityTipTextForForumModerator {
            get {
                return ResourceManager.GetString("AnnualQuantityTipTextForForumModerator", resourceCulture);
            }
        }
        
        public static string AnnualQuantityTipTextForMentorship {
            get {
                return ResourceManager.GetString("AnnualQuantityTipTextForMentorship", resourceCulture);
            }
        }
        
        public static string AnnualQuantityTipTextForOpenSource {
            get {
                return ResourceManager.GetString("AnnualQuantityTipTextForOpenSource", resourceCulture);
            }
        }
        
        public static string AnnualQuantityTipTextForOther {
            get {
                return ResourceManager.GetString("AnnualQuantityTipTextForOther", resourceCulture);
            }
        }
        
        public static string AnnualQuantityTipTextForPosts {
            get {
                return ResourceManager.GetString("AnnualQuantityTipTextForPosts", resourceCulture);
            }
        }
        
        public static string AnnualQuantityTipTextForProject {
            get {
                return ResourceManager.GetString("AnnualQuantityTipTextForProject", resourceCulture);
            }
        }
        
        public static string AnnualQuantityTipTextForSamples {
            get {
                return ResourceManager.GetString("AnnualQuantityTipTextForSamples", resourceCulture);
            }
        }
        
        public static string AnnualQuantityTipTextForSiteOwner {
            get {
                return ResourceManager.GetString("AnnualQuantityTipTextForSiteOwner", resourceCulture);
            }
        }
        
        public static string AnnualQuantityTipTextForSocialMedia {
            get {
                return ResourceManager.GetString("AnnualQuantityTipTextForSocialMedia", resourceCulture);
            }
        }
        
        public static string AnnualQuantityTipTextForSpeaking {
            get {
                return ResourceManager.GetString("AnnualQuantityTipTextForSpeaking", resourceCulture);
            }
        }
        
        public static string AnnualQuantityTipTextForTranslationReviewFeedbackEditing {
            get {
                return ResourceManager.GetString("AnnualQuantityTipTextForTranslationReviewFeedbackEditing", resourceCulture);
            }
        }
        
        public static string AnnualQuantityTipTextForForumParticipation {
            get {
                return ResourceManager.GetString("AnnualQuantityTipTextForForumParticipation", resourceCulture);
            }
        }
        
        public static string AnnualQuantityTipTextForUserGroupOwner {
            get {
                return ResourceManager.GetString("AnnualQuantityTipTextForUserGroupOwner", resourceCulture);
            }
        }
        
        public static string AnnualQuantityTipTextForVideo {
            get {
                return ResourceManager.GetString("AnnualQuantityTipTextForVideo", resourceCulture);
            }
        }
        
        public static string AnnualQuantityTipTextForWebcast {
            get {
                return ResourceManager.GetString("AnnualQuantityTipTextForWebcast", resourceCulture);
            }
        }
        
        public static string AnnualQuantityTipTextForWebsitePosts {
            get {
                return ResourceManager.GetString("AnnualQuantityTipTextForWebsitePosts", resourceCulture);
            }
        }
        
        public static string AnnualReachTipTextDefault {
            get {
                return ResourceManager.GetString("AnnualReachTipTextDefault", resourceCulture);
            }
        }
        
        public static string AnnualReachTipTextForArticle {
            get {
                return ResourceManager.GetString("AnnualReachTipTextForArticle", resourceCulture);
            }
        }
        
        public static string AnnualReachTipTextForBook {
            get {
                return ResourceManager.GetString("AnnualReachTipTextForBook", resourceCulture);
            }
        }
        
        public static string AnnualReachTipTextForConference {
            get {
                return ResourceManager.GetString("AnnualReachTipTextForConference", resourceCulture);
            }
        }
        
        public static string AnnualReachTipTextForFeedback {
            get {
                return ResourceManager.GetString("AnnualReachTipTextForFeedback", resourceCulture);
            }
        }
        
        public static string AnnualReachTipTextForForumModerator {
            get {
                return ResourceManager.GetString("AnnualReachTipTextForForumModerator", resourceCulture);
            }
        }
        
        public static string AnnualReachTipTextForMentorship {
            get {
                return ResourceManager.GetString("AnnualReachTipTextForMentorship", resourceCulture);
            }
        }
        
        public static string AnnualReachTipTextForOpenSource {
            get {
                return ResourceManager.GetString("AnnualReachTipTextForOpenSource", resourceCulture);
            }
        }
        
        public static string AnnualReachTipTextForOther {
            get {
                return ResourceManager.GetString("AnnualReachTipTextForOther", resourceCulture);
            }
        }
        
        public static string AnnualReachTipTextForPosts {
            get {
                return ResourceManager.GetString("AnnualReachTipTextForPosts", resourceCulture);
            }
        }
        
        public static string AnnualReachTipTextForProject {
            get {
                return ResourceManager.GetString("AnnualReachTipTextForProject", resourceCulture);
            }
        }
        
        public static string AnnualReachTipTextForSamples {
            get {
                return ResourceManager.GetString("AnnualReachTipTextForSamples", resourceCulture);
            }
        }
        
        public static string AnnualReachTipTextForSiteOwner {
            get {
                return ResourceManager.GetString("AnnualReachTipTextForSiteOwner", resourceCulture);
            }
        }
        
        public static string AnnualReachTipTextForSocialMedia {
            get {
                return ResourceManager.GetString("AnnualReachTipTextForSocialMedia", resourceCulture);
            }
        }
        
        public static string AnnualReachTipTextForSpeaking {
            get {
                return ResourceManager.GetString("AnnualReachTipTextForSpeaking", resourceCulture);
            }
        }
        
        public static string AnnualReachTipTextForTranslationReviewFeedbackEditing {
            get {
                return ResourceManager.GetString("AnnualReachTipTextForTranslationReviewFeedbackEditing", resourceCulture);
            }
        }
        
        public static string AnnualReachTipTextForForumParticipation {
            get {
                return ResourceManager.GetString("AnnualReachTipTextForForumParticipation", resourceCulture);
            }
        }
        
        public static string AnnualReachTipTextForUserGroupOwner {
            get {
                return ResourceManager.GetString("AnnualReachTipTextForUserGroupOwner", resourceCulture);
            }
        }
        
        public static string AnnualReachTipTextForVideo {
            get {
                return ResourceManager.GetString("AnnualReachTipTextForVideo", resourceCulture);
            }
        }
        
        public static string AnnualReachTipTextForWebcast {
            get {
                return ResourceManager.GetString("AnnualReachTipTextForWebcast", resourceCulture);
            }
        }
        
        public static string AnnualReachTipTextForWebsitePosts {
            get {
                return ResourceManager.GetString("AnnualReachTipTextForWebsitePosts", resourceCulture);
            }
        }
        
        public static string DefaultNetworkErrorString {
            get {
                return ResourceManager.GetString("DefaultNetworkErrorString", resourceCulture);
            }
        }
        
        public static string FieldMustbeNumberMessageText {
            get {
                return ResourceManager.GetString("FieldMustbeNumberMessageText", resourceCulture);
            }
        }
        
        public static string InvalidUrlMessageText {
            get {
                return ResourceManager.GetString("InvalidUrlMessageText", resourceCulture);
            }
        }
        
        public static string MaxLengthMessageText {
            get {
                return ResourceManager.GetString("MaxLengthMessageText", resourceCulture);
            }
        }
        
        public static string NetworkErrorFormatString {
            get {
                return ResourceManager.GetString("NetworkErrorFormatString", resourceCulture);
            }
        }
        
        public static string RequiredFieldMessageText {
            get {
                return ResourceManager.GetString("RequiredFieldMessageText", resourceCulture);
            }
        }
        
        public static string SecondAnnualQuantityTipTextForPosts {
            get {
                return ResourceManager.GetString("SecondAnnualQuantityTipTextForPosts", resourceCulture);
            }
        }
        
        public static string SecondAnnualQuantityTipTextForumParticipation {
            get {
                return ResourceManager.GetString("SecondAnnualQuantityTipTextForumParticipation", resourceCulture);
            }
        }
        
        public static string SecondAnnualQuantityTipTextForWebsitePosts {
            get {
                return ResourceManager.GetString("SecondAnnualQuantityTipTextForWebsitePosts", resourceCulture);
            }
        }
        
        public static string DialogTitleForSignout {
            get {
                return ResourceManager.GetString("DialogTitleForSignout", resourceCulture);
            }
        }
        
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        public static string ContributionDetailTitleForEditing {
            get {
                return ResourceManager.GetString("ContributionDetailTitleForEditing", resourceCulture);
            }
        }
        
        public static string ContributionDetailTitleForNew {
            get {
                return ResourceManager.GetString("ContributionDetailTitleForNew", resourceCulture);
            }
        }
        
        public static string CopyrightFormat {
            get {
                return ResourceManager.GetString("CopyrightFormat", resourceCulture);
            }
        }
        
        public static string DialogDescriptionForCheckNetwork {
            get {
                return ResourceManager.GetString("DialogDescriptionForCheckNetwork", resourceCulture);
            }
        }
        
        public static string DialogDescriptionForCheckNetworkFormat {
            get {
                return ResourceManager.GetString("DialogDescriptionForCheckNetworkFormat", resourceCulture);
            }
        }
        
        public static string DialogDescriptionForCheckNetworkFormat1 {
            get {
                return ResourceManager.GetString("DialogDescriptionForCheckNetworkFormat1", resourceCulture);
            }
        }
        
        public static string DialogDescriptionForError {
            get {
                return ResourceManager.GetString("DialogDescriptionForError", resourceCulture);
            }
        }
        
        public static string DialogDescriptionForInvalidCredentials {
            get {
                return ResourceManager.GetString("DialogDescriptionForInvalidCredentials", resourceCulture);
            }
        }
        
        public static string DialogDescriptionForSaved {
            get {
                return ResourceManager.GetString("DialogDescriptionForSaved", resourceCulture);
            }
        }
        
        public static string DialogDescriptionForUnableSave {
            get {
                return ResourceManager.GetString("DialogDescriptionForUnableSave", resourceCulture);
            }
        }
        
        public static string DialogLoading {
            get {
                return ResourceManager.GetString("DialogLoading", resourceCulture);
            }
        }
        
        public static string DialogOK {
            get {
                return ResourceManager.GetString("DialogOK", resourceCulture);
            }
        }
        
        public static string DialogSaving {
            get {
                return ResourceManager.GetString("DialogSaving", resourceCulture);
            }
        }
        
        public static string DialogTitleForCheckNetwork {
            get {
                return ResourceManager.GetString("DialogTitleForCheckNetwork", resourceCulture);
            }
        }
        
        public static string DialogTitleForError {
            get {
                return ResourceManager.GetString("DialogTitleForError", resourceCulture);
            }
        }
        
        public static string DialogTitleForSaved {
            get {
                return ResourceManager.GetString("DialogTitleForSaved", resourceCulture);
            }
        }
        
        public static string RefreshTokenExceptionTip {
            get {
                return ResourceManager.GetString("RefreshTokenExceptionTip", resourceCulture);
            }
        }
        
        public static string RefreshTokenTip {
            get {
                return ResourceManager.GetString("RefreshTokenTip", resourceCulture);
            }
        }
        
        public static string DialogCancel {
            get {
                return ResourceManager.GetString("DialogCancel", resourceCulture);
            }
        }
        
        public static string DialogForSignoutConfirmTipText {
            get {
                return ResourceManager.GetString("DialogForSignoutConfirmTipText", resourceCulture);
            }
        }
        
        public static string DialogForSignoutOKText {
            get {
                return ResourceManager.GetString("DialogForSignoutOKText", resourceCulture);
            }
        }
        
        public static string VersionFormat {
            get {
                return ResourceManager.GetString("VersionFormat", resourceCulture);
            }
        }
        
        public static string DialogConfirmTextForDelete {
            get {
                return ResourceManager.GetString("DialogConfirmTextForDelete", resourceCulture);
            }
        }
        
        public static string DialogDescriptionForDelete {
            get {
                return ResourceManager.GetString("DialogDescriptionForDelete", resourceCulture);
            }
        }
        
        public static string DialogTitleForDelete {
            get {
                return ResourceManager.GetString("DialogTitleForDelete", resourceCulture);
            }
        }
        
        public static string DialogTitleForLoadingContribution {
            get {
                return ResourceManager.GetString("DialogTitleForLoadingContribution", resourceCulture);
            }
        }
        
        public static string DialogTitleForLoadingProfile {
            get {
                return ResourceManager.GetString("DialogTitleForLoadingProfile", resourceCulture);
            }
        }
        
        public static string ExpectedCultureIdentifier {
            get {
                return ResourceManager.GetString("ExpectedCultureIdentifier", resourceCulture);
            }
        }
        
        public static string TabTitleForContributions {
            get {
                return ResourceManager.GetString("TabTitleForContributions", resourceCulture);
            }
        }
        
        public static string TabTitleForProfile {
            get {
                return ResourceManager.GetString("TabTitleForProfile", resourceCulture);
            }
        }
        
        public static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        public static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        public static string DevToolsInfo {
            get {
                return ResourceManager.GetString("DevToolsInfo", resourceCulture);
            }
        }
        
        public static string LabelForAwardCategories {
            get {
                return ResourceManager.GetString("LabelForAwardCategories", resourceCulture);
            }
        }
        
        public static string LabelForContributionArea {
            get {
                return ResourceManager.GetString("LabelForContributionArea", resourceCulture);
            }
        }
        
        public static string LabelForContributionDate {
            get {
                return ResourceManager.GetString("LabelForContributionDate", resourceCulture);
            }
        }
        
        public static string LabelForContributionTitle {
            get {
                return ResourceManager.GetString("LabelForContributionTitle", resourceCulture);
            }
        }
        
        public static string LabelForContributionType {
            get {
                return ResourceManager.GetString("LabelForContributionType", resourceCulture);
            }
        }
        
        public static string LabelForDescription {
            get {
                return ResourceManager.GetString("LabelForDescription", resourceCulture);
            }
        }
        
        public static string LabelForFirstAward {
            get {
                return ResourceManager.GetString("LabelForFirstAward", resourceCulture);
            }
        }
        
        public static string LabelForNumberOfAward {
            get {
                return ResourceManager.GetString("LabelForNumberOfAward", resourceCulture);
            }
        }
        
        public static string LabelForURL {
            get {
                return ResourceManager.GetString("LabelForURL", resourceCulture);
            }
        }
        
        public static string LabelForVisibility {
            get {
                return ResourceManager.GetString("LabelForVisibility", resourceCulture);
            }
        }
        
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        public static string PageTitleForLogOn {
            get {
                return ResourceManager.GetString("PageTitleForLogOn", resourceCulture);
            }
        }
        
        public static string PageTitleForSetting {
            get {
                return ResourceManager.GetString("PageTitleForSetting", resourceCulture);
            }
        }
        
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        public static string SettingsButton {
            get {
                return ResourceManager.GetString("SettingsButton", resourceCulture);
            }
        }
        
        public static string SigninTo {
            get {
                return ResourceManager.GetString("SigninTo", resourceCulture);
            }
        }
        
        public static string SignoutButton {
            get {
                return ResourceManager.GetString("SignoutButton", resourceCulture);
            }
        }
        
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
